apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service2
  labels:
    app: fastapi-service2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi-service2
  template:
    metadata:
      labels:
        app: fastapi-service2
    spec:
      containers:
        - name: fastapi-service2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2222
              hostPort: 2222
