apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service1
  labels:
    app: fastapi-service1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi-service1
  template:
    metadata:
      labels:
        app: fastapi-service1
    spec:
      containers:
        - name: fastapi-service1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1111
