apiVersion: v1
kind: Service
metadata:
  name: fastapi-service1
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fastapi-service1 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP