apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service1
  labels:
    app: fastapi-service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-service1
  template:
    metadata:
      labels:
        app: fastapi-service1
    spec:
      containers:
        - name: fastapi-service1
          image: fastapi-service1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
